Setup and mobile first
Kidd254/Lawrence-s-Portfolio pull request #1
Opened 2022-11-30 19:31 UTC by Kidd254

in this branch, i created css, html, gitignore and README files for the purpose of the project. i also added es linter configuration files to format my css file to the popular styling format

2022-11-30 20:23 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Kidd254 , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media0.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif"/> |

## Highlights

- [ ]... ✅ Good commit messages
- [ ]... ✅  Linters have passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 20:23 UTC, joskalenda commented on index.html
> +                <div>
- [ ] Kindly change this logo name by putting yours since the application is owned by you now, in addition to this, please wrap this logo name in an `a` tag, this is to allow the user to navigate to the home page.

2022-11-30 20:23 UTC, joskalenda commented on index.html
> +                hestiate to contact me.</div>
- [ ] Well done on creating this section, however, it is required to use a `p` tag for this text, kindly modify this div into a `p`

2022-11-30 20:23 UTC, joskalenda commented on style.css
> +
- [ ] Your design looks good but not better, I think you can still improve it, please take a look at these 2 images right here and implement the following mentioned changes.
- [ ] Take a look closer at the text in the red border, we can see that the font and the alignment are different, please update your design using the same and correct Figma properties
- [ ] At the bottom of the page, there is a left-border-radius which is not in your design, please fix that one to as we move onto the next phases of the project
> |Figma on the left and your design on the right |
> |---|
> | <img width="728" alt="two" src="https://user-images.githubusercontent.com/77843050/204899532-0f5fa633-879b-43c3-8912-a5d5743ac8ce.png"> |

2022-11-30 20:23 UTC, joskalenda commented on README.md
> +    LinkedIn: Lawrence Kioko
- [ ] Kindly add your correct social media links

2022-12-01 17:38 UTC, Gopxfs commented
# STATUS: INVALID REQUEST

Hi @Kidd254 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a PR that was used for a different feature.

Your Code Review Request will be marked invalid in your Dashboard, so please submit a new one once ready 🙏.
Invalid requests don't count as a review, so don't worry about that 😄!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-01 17:51 UTC, tugsem approved these changes
## STATUS: APPROVED 👍🎯  
Hi @Kidd254 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️  Changes applied
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 18:50 UTC, merged