Finish mobile version
Kidd254/Lawrence-s-Portfolio pull request #2
Opened 2022-12-01 19:39 UTC by Kidd254

in this pull request, i modified, html and css files

2022-12-01 20:08 UTC, huseyinbiyik commented
Hi @Kidd254,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly use this template and update all the sections according to your project. You can use find the template on this [link](https://github.com/microverseinc/readme-template#built-with). Your section headings are not there and the links on the top are not working. Also, kindly add a link to your license file.
- Please fix the PR description and try to be more descriptive it needs to include what changes were made on this branch.
- Please use a more descriptive commit description for your next commits. So you can keep your project history in a more professional way.
<img width="375" alt="Screenshot 2022-12-01 at 11 07 48 PM" src="https://user-images.githubusercontent.com/25887253/205149456-f66a4a54-ce12-42f4-bc60-aa21f21c425f.png">

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-02 20:23 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @Kidd254 , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- You did a great job on your design it looks nice however the are some issues you need to fix so that it will make your design stick to the Figma design as required in the project  :+1: :grinning: :grinning: :grinning: 
  - Kindly make  your design  responsive by removing those spaces around the body  of your page for doing that I can suggest you not use the fix for the main container of your project, and make  your page take the max screen at 100%
  - Kindly add also the about section on your page as it is also part of the requirement :+1: 


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-02 20:23 UTC, MaganaAsiati commented on index.html
> +                </div>
- You did a great job by making the list of technology in the ` div ` however I can suggest for the best practices to use  `<ul> and  <li>`  tags  when you structure your list so The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li :+1:

2022-12-02 20:23 UTC, MaganaAsiati commented on index.html
> +                </div>
- You did a great job by making the list of technology in the ` div ` however I can suggest for the best practices to use  `<ul> and  <li>`  tags  when you structure your list so The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li :+1:

2022-12-02 20:23 UTC, MaganaAsiati commented on index.html
> +                <div class="action">
- You did a great job by making the list of technology in the ` div ` however I can suggest for the best practices to use  `<ul> and  <li>`  tags  when you structure your list so The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list ul and each of them a li :+1:

2022-12-02 21:16 UTC, Kidd254 commented
hello @MaganaAsiati, about (making your design responsive by removing those spaces around the body of your page for doing that I can suggest you not use the fix for the main container of your project, and make your page take the max screen at 100%) we are yet to cover responsive web design...

2022-12-02 21:37 UTC, frank1738 approved these changes
Hi @Kidd254 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/StL3vbwXU21ONOA3Ue/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good design 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 22:07 UTC, merged